
version: '3.8'

services:
    backend:
      build: ./backend
      ports:
        - "3000:3000"
      container_name: node-backend
      restart : always

    frontend:
      build: ./frontend
      ports:
        - "5173:5173"
      container_name: react-frontend
      restart : always


    mongo:
      image: mongo:latest
      container_name: mongo
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
      restart: always

volumes:
  mongo-data: